---
title: "Fixed effect BLUEs"
author: "Harly Durbin"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(tidyr)
library(stringr)
library(dplyr)
library(glue)
library(readxl)
library(magrittr)
library(tidylog)

source(here::here("source_functions/melt_aireml.R"))
source(here::here("source_functions/parse_renf90table.R"))

```

# Notes & questions

## Model key

* `fixed1`
    + `{farm_id} + {year} + {calving_season} + {age} + {days_from_May1} + {toxic_fescue} + {latitude}`. Everything would be fit as a categorical factor, except for days from May 1 and latitude

# Setup 

```{r, warning=FALSE, message=FALSE}
cleaned <- read_rds(here::here("data/derived_data/import_join_clean/cleaned.rds"))
```

```{r, warning=FALSE, message=FALSE}
full_ped <- read_rds(here::here("data/derived_data/3gen/full_ped.rds"))
```

```{r, warning=FALSE, message=FALSE}
fixed1_key <-
  c(1:7) %>% 
  purrr::map_dfr(~ parse_renf90table(here::here("data/derived_data/base_varcomp/fixed1/renf90.tables"),
                                     effect_num = .x,
                                     effect_key = TRUE))
  
```

```{r}
fixed1_sol <-
  read_ta
```


