---
title: "Simmental cleanup transfers"
author: "Harly Durbin"
date: "10/29/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(readxl)
library(tidyr)
library(purrr)
library(dplyr)
library(tidylog)

source(here::here("source_functions/animal_table.R"))
source(here::here("source_functions/tissue_table.R"))
```

# Setup

```{r}
animal_table <- get_animal_table("190907")

write_rds(animal_table, here::here("data/derived_data/animal_table.rds"))
```

```{r, echo=TRUE, eval = FALSE}
tissue <- get_tissue("190907")

write_rds(tissue, here::here("data/derived_data/tissue.rds"))
```

```{r sent, message=FALSE, warning=FALSE, results='hide'}
source(here::here("source_functions/sent_samples.R"))
```

```{r}
sent2 <-
  sent %>%
  left_join(animal_table %>%
              select(Lab_ID,
                     Reg,
                     Ref_ID,
                     Ref_ID2,
                     breed_assoc_reg))
```


# Reformat file Jared created

```{r}

read_csv("~/Box Sync/HairShedding/ReportedData/SendToBreedAssociations/20190830.SIM.csv") %>% 
  janitor::clean_names() %>% 
  rename(Reg = a_s_a_registration_number) %>% 
  mutate(
    Reg = as.character(Reg),
    Reg = if_else(is.na(Reg), barcode, Reg)
    ) %>% 
  left_join(animal_table) %>% 
  select(
    Lab_ID,
    Reg,
    Barcode = Ref_ID2,
    Ref_ID, 
    Ref_ID_source,
    BC,
    Sex,
    DOB,
    Sire_Reg,
    Dam_Reg,
    registered,
    breed_assoc
    ) %>% 
  mutate(
    source_code = "GIB",
    assoc_code = "SIM"
  ) %>% 
  filter(!is.na(Ref_ID)) %>%
  writexl::write_xlsx("~/Box Sync/HairShedding/ReportedData/SendToBreedAssociations/20191029.SIM.xlsx")
  
  

```

```{r}
sim_transfers <-
  c(
    "~/Box Sync/HairShedding/ReportedData/SendToBreedAssociations/20191029.SIM.xlsx",
    "~/Box Sync/HairShedding/ReportedData/SendToBreedAssociations/20191004.SIM.xlsx",
    "~/Box Sync/HairShedding/ReportedData/SendToBreedAssociations/20190708.SIM.xlsx",
    "~/Box Sync/HairShedding/ReportedData/SendToBreedAssociations/20190708.SIM_retest.xlsx",
    "~/Box Sync/HairShedding/ReportedData/SendToBreedAssociations/20190625.SIM.xlsx",
    "~/Box Sync/HairShedding/ReportedData/SendToBreedAssociations/20181106.SIM.xlsx",
    "~/Box Sync/HairShedding/ReportedData/SendToBreedAssociations/20181218.SIM.xlsx",
    "~/Box Sync/HairShedding/ReportedData/SendToBreedAssociations/20190108.SIM.xlsx",
    "~/Box Sync/HairShedding/ReportedData/SendToBreedAssociations/20190312.SIM.xlsx"
  ) %>%
  set_names(
    c(
      "20191029",
      "20191004",
      "20190708",
      "20190708_retest",
      "20190625",
      "20181106",
      "20181218",
      "20190108",
      "20190312"
    )
  ) %>%
  purrr::map_dfr( ~ read_excel(.x, col_types = "text"), .id = "transfer_date") %>%
  bind_rows(
    c(
      "~/Box Sync/HairShedding/ReportedData/SendToBreedAssociations/180306_sim_transfer.csv",
      "~/Box Sync/HairShedding/ReportedData/SendToBreedAssociations/180823.SIM.csv",
      "~/Box Sync/HairShedding/ReportedData/SendToBreedAssociations/sim_20180329.csv"
    ) %>%
      set_names(c("20180306",
                  "20180823",
                  "20180329")) %>%
      purrr::map_dfr( ~ read_csv(.x, col_types = cols(.default = "c")), .id = "transfer_date") %>%
      mutate(
        Farm_ID = if_else(!is.na(Farm_name), Farm_name, Farm_ID),
        Barcode = if_else(
          !is.na(`180306_sim_transfer_Barcode`),
          `180306_sim_transfer_Barcode`,
          Barcode
        ),
        Ref_ID = if_else(!is.na(Animal_ID), Animal_ID, Ref_ID)
      ) %>%
      select(
        transfer_date,
        source_code = Farm_ID,
        Reg,
        BC,
        Barcode,
        breed_assoc,
        Lab_ID,
        Ref_ID,
        Ref_ID_source,
        Sex
      ) %>% 
      mutate(transfer_date = lubridate::ymd(transfer_date)) %>% 
      group_by(Reg) %>% 
      filter(transfer_date == max(transfer_date)) %>% 
      ungroup() %>% 
      mutate(transfer_date = as.character(transfer_date))
      
  )
```

```{r}
sim_transfers %>% 
  group_by(Reg) %>% 
  filter(n() > 1) %>% 
  arrange(Reg)
```


```{r}
read_excel(here::here("data/raw_data/Gibbs Farms - Cow Herd - No GE Reported (as of 10-24-19).xls"), skip = 2) %>% 
  left_join(sim_transfers %>% 
              select(transfer_date, Reg),
            by = c("ASA" = "Reg")) %>% 
  mutate(
    transfer_date = 
      case_when(
        transfer_date == "20191029" ~ lubridate::ymd("20190830"),
        TRUE ~ lubridate::ymd(transfer_date))
    ) %>% 
  writexl::write_xlsx("~/Desktop/20191029.gibbs_no_ge.xlsx")
```

```{r}
read_excel(
  here::here(
    "data/raw_data/Gibbs Farms - Cow Herd - No GE Reported (as of 10-24-19).xls"
  ),
  skip = 2
) %>%
  left_join(sim_transfers %>%
              select(transfer_date, Reg),
            by = c("ASA" = "Reg")) %>%
  mutate(transfer_date =
           case_when(
             transfer_date == "20191029" ~ lubridate::ymd("20190830"),
             TRUE ~ lubridate::ymd(transfer_date)
           )) %>%
  filter(is.na(transfer_date)) %>%
  left_join(sent2,
            by = c("ASA" = "Reg"))
```

```{r}
read_excel(
  here::here(
    "data/raw_data/Gibbs Farms - Cow Herd - No GE Reported (as of 10-24-19).xls"
  ),
  skip = 2
) %>%
  left_join(sim_transfers %>%
              select(transfer_date, Reg),
            by = c("ASA" = "Reg")) %>%
  mutate(transfer_date =
           case_when(
             transfer_date == "20191029" ~ lubridate::ymd("20190830"),
             TRUE ~ lubridate::ymd(transfer_date)
           )) %>%
  filter(is.na(transfer_date)) %>% 
  filter(Tattoo %in% sent2$Ref_ID)
  
```

# 11/24/20 Pull out ASA breeding values for Jared

```{r}
breed_key <- read_rds(here::here("data/derived_data/breed_key/breed_key.rds"))
```

```{r}
full_ped <- read_rds(here::here("data/derived_data/3gen/full_ped.rds"))
```

```{r}
animal_table <- read_rds(here::here("data/raw_data/import_join_clean/animal_table.rds"))
```

```{r}
cleaned <- read_rds(here::here("data/derived_data/import_join_clean/cleaned.rds"))
```

```{r}
source(here::here("source_functions/calculate_acc.R"))
```

```{r}
source(here::here("source_functions/three_gen.R"))
```

```{r}
genotyped <- 
  read_csv(here::here("data/derived_data/grm_inbreeding/mizzou_hairshed.diagonal.full_reg.csv")) %>% 
  mutate(genotype_used = TRUE)
```


## Pedigree inbreeding

```{r}

pedinb <-
  full_ped %>% 
  select(full_reg, sire_reg, dam_reg) %>%
  optiSel::prePed() %>%
  optiSel::pedInbreeding() %>%
  tibble::remove_rownames() %>%
  rename(full_reg = Indiv,
         f = Inbr)
```


## From full dataset

```{r}
full_bvs <-
  read_table2(here::here("data/derived_data/aireml_varcomp/fixed9/solutions"),
              skip = 1,
              col_names = c("trait", "effect", "id_renamed", "solution", "se")) %>% 
  filter(effect == 2) %>% 
  left_join(read_table2(here::here("data/derived_data/aireml_varcomp/fixed9/renadd02.ped"),
                        col_names = FALSE) %>% 
              select(id_renamed = X1, full_reg = X10)) %>% 
  select(-trait, -effect, -id_renamed) %>% 
  left_join(pedinb) %>%
  mutate(f = tidyr::replace_na(f, 0),
         acc = purrr::map2_dbl(.x = se,
                               .y = f,
                               ~ calculate_acc(u = 0.33133,
                                               se = .x,
                                               f = .y,
                                               option = "bif")),
         acc = if_else(0 > acc, 0, acc))
```

```{r}
full_pull <-
  full_bvs %>% 
  left_join(breed_key %>% 
              select(Lab_ID:brd_source)) %>% 
  filter(!farm_id %in% c("SAV", "BAT")) %>% 
  left_join(animal_table %>% 
              select(Lab_ID, BC, breed_assoc, international_id)) %>% 
  mutate(keep = case_when(str_detect(full_reg, "SIM") ~ TRUE,
                          source == "American Simmental Association" ~ TRUE,
                          brd_source == "American Simmental Association" ~ TRUE,
                          breed_assoc == "American Simmental Association" ~ TRUE,
                          str_detect(international_id, "SIM") ~ TRUE,
                          TRUE ~ FALSE)) %>% 
  filter(keep == TRUE) %>% 
  left_join(full_ped %>% 
              select(full_reg, sire_reg, dam_reg)) %>% 
  select(full_reg, sire_reg, dam_reg) %>% 
  three_gen(full_ped = full_ped)
```

```{r}
full_out <-
  full_pull %>% 
  select(full_reg) %>% 
  bind_rows(full_pull %>% 
              select(full_reg = sire_reg)) %>% 
  bind_rows(full_pull %>% 
              select(full_reg = dam_reg)) %>% 
  distinct() %>% 
  left_join(full_bvs) %>% 
  filter(!is.na(solution)) %>% 
  left_join(breed_key %>% 
              select(full_reg, farm_id, animal_id)) %>% 
  left_join(genotyped %>% 
              select(-diagonal)) %>% 
  left_join(readxl::read_excel(here::here("data/raw_data/farm_numbers.xlsx")) %>% 
              select(Farm, farm_id = Farm_ID, contact = Name) %>% 
              filter(!is.na(farm_id))) %>% 
  mutate(epd = solution/2,
         genotype_used = if_else(is.na(genotype_used), FALSE, genotype_used),
         contact = str_to_title(contact),
         full_reg = str_replace(full_reg, "^RAN", "RAAA")) %>% 
  filter(!str_detect(full_reg, "^BSH|^BRM|^HER|^CHA")) %>% 
  mutate(full_reg = if_else(!str_detect(full_reg, "^RAAA|^SIM|^AAA|^CIA"), NA_character_, full_reg)) %>% 
  select(farm_id = Farm, contact, registration_number = full_reg, animal_id, epd, bif_acc = acc, genotype_used) %>% 
  arrange(farm_id, registration_number)


```

## From IGS dataset

```{r}
igs_bvs <-
  read_table2(here::here("data/derived_data/aireml_varcomp/igs1/solutions"),
              skip = 1,
              col_names = c("trait", "effect", "id_renamed", "solution", "se")) %>% 
  filter(effect == 2) %>% 
  left_join(read_table2(here::here("data/derived_data/aireml_varcomp/igs1/renadd02.ped"),
                        col_names = FALSE) %>% 
              select(id_renamed = X1, full_reg = X10)) %>% 
  select(-trait, -effect, -id_renamed) %>% 
  left_join(pedinb) %>%
  mutate(f = tidyr::replace_na(f, 0),
         acc = purrr::map2_dbl(.x = se,
                               .y = f,
                               ~ calculate_acc(u = 0.39053,
                                               se = .x,
                                               f = .y,
                                               option = "bif")),
         acc = if_else(0 > acc, 0, acc))
```

```{r}
igs_pull <-
  igs_bvs %>% 
  left_join(breed_key %>% 
              select(Lab_ID:brd_source)) %>% 
  filter(!farm_id %in% c("SAV", "BAT")) %>% 
  left_join(animal_table %>% 
              select(Lab_ID, BC, breed_assoc, international_id)) %>% 
  mutate(keep = case_when(str_detect(full_reg, "SIM") ~ TRUE,
                          source == "American Simmental Association" ~ TRUE,
                          brd_source == "American Simmental Association" ~ TRUE,
                          breed_assoc == "American Simmental Association" ~ TRUE,
                          str_detect(international_id, "SIM") ~ TRUE,
                          TRUE ~ FALSE)) %>% 
  filter(keep == TRUE) %>% 
  left_join(full_ped %>% 
              select(full_reg, sire_reg, dam_reg)) %>% 
  select(full_reg, sire_reg, dam_reg) %>% 
  three_gen(full_ped = full_ped)
```

```{r}
igs_out <-
  igs_pull %>% 
  select(full_reg) %>% 
  bind_rows(igs_pull %>% 
              select(full_reg = sire_reg)) %>% 
  bind_rows(igs_pull %>% 
              select(full_reg = dam_reg)) %>% 
  distinct() %>% 
  left_join(igs_bvs) %>% 
  filter(!is.na(solution)) %>% 
  left_join(breed_key %>% 
              select(full_reg, farm_id, animal_id)) %>% 
  left_join(genotyped %>% 
              select(-diagonal)) %>% 
  left_join(readxl::read_excel(here::here("data/raw_data/farm_numbers.xlsx")) %>% 
              select(Farm, farm_id = Farm_ID, contact = Name) %>% 
              filter(!is.na(farm_id))) %>% 
  mutate(epd = solution/2,
         genotype_used = if_else(is.na(genotype_used), FALSE, genotype_used),
         contact = str_to_title(contact),
         full_reg = str_replace(full_reg, "^RAN", "RAAA")) %>% 
  filter(!str_detect(full_reg, "^BSH|^BRM|^HER|^CHA")) %>% 
  mutate(full_reg = if_else(!str_detect(full_reg, "^RAAA|^SIM|^AAA|^CIA"), NA_character_, full_reg)) %>% 
  select(farm_id = Farm, contact, registration_number = full_reg, animal_id, epd, bif_acc = acc, genotype_used) %>% 
  arrange(farm_id, registration_number)


```

## Export

```{r}
writexl::write_xlsx(x = list("Full dataset" = full_out, "IGS only dataset" = igs_out), path = here::here("data/derived_data/201124.sim_epd.xlsx"))
```

