---
title: "Body condition score data"
author: "Harly Durbin"
date: "9/26/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(tidyr)
library(dplyr)
library(readxl)
```

# Notes & questions

* Getting BCS data together for Katelyn's undergrad project

# Setup

```{r}
cleaned <- readr::read_rds(here::here("data/derived_data/import_join_clean/cleaned.rds"))
```

# RHF data

## 2020

```{r}
# Sheet with data from cows
rhbcs20 <-
  read_excel("~/Box Sync/HairShedding/ReportedData/2020/DataRecording_RHF_2020.xlsx") %>% 
  janitor::clean_names() %>% 
  select(animal_id) %>% 
  # Remove if no BCS
  # Remove punctuation from animal IDs to match cleaned
  mutate(animal_id = stringr::str_remove_all(animal_id, "[[:punct:]]|[[:space:]]")) %>% 
  left_join(cleaned %>% 
              filter(farm_id == "RHF") %>% 
              filter(year == 2020) %>% 
              select(year, farm_id, breed_code, registration_number, Lab_ID, animal_id)) %>% 
  mutate(year = 2020,
         farm_id = "RHF",
         registration_number = if_else(animal_id == "357G",
                                       "3666958",
                                       registration_number),
         breed_code = if_else(animal_id == "357G",
                                       "SIM",
                                       breed_code),
         bcs = NA_integer_) 
```

## 2019

```{r}
# Sheet with data from cows
rhbcs19 <-
  read_excel("~/Box Sync/HairShedding/ReportedData/2019/DataRecording_RHF_2019.xlsx",
             sheet = "original_old") %>% 
  janitor::clean_names() %>% 
  select(animal_id, bcs) %>% 
  # Sheet with data from heifers
  bind_rows(read_excel("~/Box Sync/HairShedding/ReportedData/2019/DataRecording_RHF_2019.xlsx",
                       sheet = "Original_heifers") %>% 
              janitor::clean_names() %>% 
              select(animal_id = tattoo, bcs)) %>% 
  # Remove if no BCS
  filter(!is.na(bcs)) %>% 
  # Remove punctuation from animal IDs to match cleaned
  mutate(animal_id = stringr::str_remove_all(animal_id, "[[:punct:]]|[[:space:]]")) %>% 
  left_join(cleaned %>% 
              filter(farm_id == "RHF") %>% 
              filter(year == 2019) %>% 
              select(year, farm_id, breed_code, registration_number, Lab_ID, animal_id)) 
```

## 2018

```{r}
rhbcs18 <-
  read_excel("~/Box Sync/HairShedding/ReportedData/2018/DataRecording_RHF_2018.xlsx",
             sheet = "original") %>% 
  janitor::clean_names() %>% 
  select(animal_id, bcs) %>% 
  # Remove if no BCS
  filter(!is.na(bcs)) %>% 
  # Remove punctuation from animal IDs to match cleaned
  mutate(animal_id = stringr::str_remove_all(animal_id, "[[:punct:]]|[[:space:]]")) %>% 
  left_join(cleaned %>% 
              filter(farm_id == "RHF") %>% 
              filter(year == 2018) %>% 
              select(year, farm_id, breed_code, registration_number, Lab_ID, animal_id)) 
  
```

## 2017

```{r}
rhbcs17 <-
  read_excel("~/Box Sync/HairShedding/ReportedData/2017/DataRecording_RHF_2017.xlsx",
             sheet = "original") %>% 
  janitor::clean_names() %>% 
  select(animal_id, bcs) %>% 
  # Remove if no BCS
  filter(!is.na(bcs)) %>% 
  # Remove punctuation and spacesfrom animal IDs to match cleaned
  mutate(animal_id = stringr::str_remove_all(animal_id, "[[:punct:]]|[[:space:]]")) %>% 
  left_join(cleaned %>% 
              filter(farm_id == "RHF") %>% 
              filter(year == 2017) %>% 
              select(year, farm_id, breed_code, registration_number, Lab_ID, animal_id))

```

## Export

```{r}
bind_rows(rhbcs17, rhbcs18, rhbcs19, rhbcs20) %>% 
  write_csv("~/Box Sync/HairShedding/BCS/data/raw_data/rhf_bcs.csv", na = "")
```

