---
title: "Breed-specific ssGBLUP, GWAS, and meta-analysis"
author: "Harly Durbin"
output:
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
    df_print: paged
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
library(readr)
library(tidyr)
library(stringr)
library(dplyr)
library(ggplot2)
library(glue)
library(readxl)
library(magrittr)
library(tidylog)
library(rlang)

source(here::here("source_functions/melt_aireml.R"))
source(here::here("source_functions/calculate_heritability.R"))
source(here::here("source_functions/hair_manhattan.R"))

options(scipen = 999)
```

# Notes & questions

* Angus: #126180
* IGS: #B578A6
* Hereford: #F57195
* Brangus: #4EB7B8

## Datasets

* Hereford
* Participating IGS breed associations
    + RAN, SIM, GEL, SH, CHI
* Brangus
* Angus
    
```{r, eval=FALSE}
scales::show_col(bakeoff::bakeoff_pal()(11))
```
    
    
# Setup

## Raw GWAS results

```{r, warning=FALSE, message=FALSE}
breed_gwas <-
  c("hfd1", "an1", "bg1", "igs1") %>% 
  purrr::set_names() %>% 
  purrr::map_dfr(~ read_table2(here::here(glue("data/derived_data/snp1101/{.x}/out/gwas_ssr_{.x}_bvs_p.txt")))  %>%
                   janitor::clean_names() %>%
                   mutate(neglog10p = -log10(p_value),
                          neglog10q = -log10(qvalue::qvalue(p_value)$qvalues)) %>%
                   left_join(read_table2(here::here(glue("data/derived_data/snp1101/{.x}/out/gwas_ssr_{.x}_bvs.txt")),
                                         skip = 12) %>%
                               select(chr = Chr, pos = Pos, fdr = FDR_GW, a)),
                 .id = "dataset")
```

## `METASOFT`

```{r, warning=FALSE, message=FALSE, eval=FALSE}

metasoft_in <-
  purrr::map2(.x = c("an1", "bg1", "hfd1", "igs1"),
              .y = c(3079, 882, 1009, 4375),
              ~ breed_gwas %>% 
                filter(dataset == .x) %>% 
                mutate(id = glue("{chr}:{pos}"),
                       se = sqrt(var/.y)) %>%
                select(id, !!rlang::sym(glue("{.x}_b")) := b_value, !!rlang::sym(glue("{.x}_se")) := se)) %>% 
  purrr::reduce(left_join) %>% 
  mutate_if(is.numeric, ~ if_else(. == 0, na_dbl, .))

```

```{r, eval=FALSE}
write_tsv(metasoft_in, here::here("data/derived_data/metasoft/breeds/metasoft_in.breeds.txt"),
          col_names = FALSE)
```

# Heritability and repeatability

```{r, warning=FALSE, message=FALSE}
purrr::map2_dfr(.x = c("hfd1", "an1", "bg1", "igs1"),
                .y = c("Hereford", "Angus", "Brangus", "IGS breeds"),
                ~ read_table2(here::here(glue("data/derived_data/aireml_varcomp/{.x}/data.txt")),
                              col_names = FALSE) %>% 
                  summarise(`n phenotypes` = n(),
                            `n phenotyped animals` = n_distinct(X1),
                            key = .y)) %>% 
  left_join(purrr::map2_dfr(.x = c("hfd1", "an1", "bg1", "igs1"),
                            .y = c("Hereford", "Angus", "Brangus", "IGS breeds"),
                            ~ read_table2(here::here(glue("data/derived_data/aireml_varcomp/{.x}/pull_list.txt")),
                                          col_names = FALSE) %>% 
                              summarise(`n genotyped` = n(),
                                        key = .y))) %>% 
  mutate_if(is.numeric, ~ scales::comma(.)) %>% 
  select(key, everything()) 
```

```{r, warning = FALSE, message = FALSE}
breed_h2 <-
  purrr::map2_dfr(.x = c("hfd1", "an1", "bg1", "igs1", "fixed9"),
                  .y = c("Hereford", "Angus", "Brangus", "IGS breeds", "Full dataset"),
                  ~ melt_aireml(path = here::here(glue("data/derived_data/aireml_varcomp/{.x}/airemlf90.{.x}.log")),
                                effect2 = c("hair_dir"),
                                effect3 = c("hair_pe"),
                                resids = c("hair_res")) %>% 
                    univ_heritability(abbrv = "hair",
                                      desc = .y,
                                      pe = TRUE))

```

```{r}
breed_h2 %>% 
  left_join(purrr::map2_dfr(.x = c("hfd1", "an1", "bg1", "igs1", "fixed9"),
                            .y = c("Hereford", "Angus", "Brangus", "IGS breeds", "Full dataset"),
                            ~ melt_aireml(path = here::here(glue("data/derived_data/aireml_varcomp/{.x}/airemlf90.{.x}.log")),
                                          effect2 = c("hair_dir"),
                                          effect3 = c("hair_pe"),
                                          resids = c("hair_res")) %>% 
                              mutate(key = .y)) %>% 
              filter(val1 == val2) %>% 
              select(-val1) %>% 
              tidyr::pivot_wider(values_from = var_cov,
                                 names_from = val2,
                                 id_cols = key)) %>% 
  select(key, `Direct var.` = hair_dir, `PE var.` = hair_pe, `Residual var.` = hair_res, `Direct h2`, Repeatability) %>% 
  add_row(key = "AGI dataset", `Direct var.` = 0.37679, `PE var.` = 0.039171, `Residual var.` = 0.53274, `Direct h2` = 0.40, Repeatability = 0.44)
```

# GWAS

## Hereford

```{r, fig.width = 11, fig.height = 6.16}
  hair_manhattan(df = breed_gwas %>% 
                   filter(dataset == "hfd1"),
                 y_var = neglog10q, 
                 y_lab = "-log10(q-value)",
                 sigline = 1,
                 color1 = "gray1",
                 color2 = "gray91")
```

## Angus

```{r, fig.width = 11, fig.height = 6.16}
  hair_manhattan(df = breed_gwas %>% 
                   filter(dataset == "an1"),
                 y_var = neglog10q, 
                 y_lab = "-log10(q-value)",
                 sigline = 1,
                 color1 = "gray1",
                 color2 = "gray91")
```

## IGS

```{r, fig.width = 11, fig.height = 6.16}
  hair_manhattan(df = breed_gwas %>% 
                   filter(dataset == "igs1"),
                 y_var = neglog10q, 
                 y_lab = "-log10(q-value)",
                 sigline = 1,
                 color1 = "gray1",
                 color2 = "gray91")
```

## Brangus

```{r, fig.width = 11, fig.height = 6.16}
  hair_manhattan(df = breed_gwas %>% 
                   filter(dataset == "bg1"),
                 y_var = neglog10q, 
                 y_lab = "-log10(q-value)",
                 sigline = 1,
                 color1 = "gray1",
                 color2 = "gray91")
```


# `METASOFT`

```
srun java -jar source_functions/Metasoft/Metasoft.jar -pvalue_table source_functions/Metasoft/HanEskinPvalueTable.txt -input data/derived_data/metasoft/breeds/metasoft_in.breeds.txt -output data/derived_data/metasoft/breeds/metasoft_out.breeds.txt -mvalue -log data/derived_data/metasoft/breeds/metasoft.breeds.log
```

```{r}
metasoft_out <- 
  read_table2(here::here("data/derived_data/metasoft/breeds/"))
```
