---
title: "COJO"
author: "Harly Durbin"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Setup 

```{r, eval=FALSE}
bim <- 
  read_table2(here::here("data/raw_data/geno_dump/200924_HairShed.850K.qc.bim"),
              col_names = FALSE) %>% 
  select(chr = X1, SNP = X2, pos = X4, A1 = X5, A2 = X6)
```

```{r, warning = FALSE, message=FALSE}
fixed9_snp1101 <-
  read_table2(here::here("data/derived_data/snp1101/fixed9/out/gwas_ssr_fixed9_bvs_p.txt"))  %>%
  janitor::clean_names() %>%
  mutate(neglog10p = -log10(p_value),
         abs_snp = abs(b_value),
         neglog10q = -log10(qvalue::qvalue(p_value)$qvalues)) %>%
  left_join(read_table2(here::here("data/derived_data/snp1101/fixed9/out/gwas_ssr_fixed9_bvs.txt"),
                        skip = 12) %>%
              select(chr = Chr, pos = Pos, fdr = FDR_GW, contains("g")))
  
```

```{r}
breeds_snp1101 <-
  c("hfd1", "an1", "bg1", "igs1") %>% 
  purrr::set_names() %>% 
  purrr::map_dfr(~ read_table2(here::here(glue("data/derived_data/snp1101/{.x}/out/gwas_ssr_{.x}_bvs_p.txt")))  %>%
                   janitor::clean_names() %>%
                   mutate(neglog10p = -log10(p_value),
                          neglog10q = -log10(qvalue::qvalue(p_value)$qvalues)) %>%
                   left_join(read_table2(here::here(glue("data/derived_data/snp1101/{.x}/out/gwas_ssr_{.x}_bvs.txt")),
                                         skip = 12) %>%
                               select(chr = Chr, pos = Pos, fdr = FDR_GW, contains("g"))),
                 .id = "dataset")
```

## COJO input

```{r, eval=FALSE}
fixed9_snp1101 %>% 
  mutate(N = g0+g1+g2) %>%
  left_join(bim) %>% 
  select(SNP, A1, A2, freq, b = b_value, var, p = p_value, N) %>% 
  write_delim(here::here("data/derived_data/cojo/fixed9/fixed9.ma"),
              delim = " ")

```

```
srun --account deckerlab -p BioCompute,htc4,hpc5 -t 48:00:00 --mem 100G -c 56 source_functions/gcta_1.93.2beta/gcta64 --bfile data/raw_data/geno_dump/200924_HairShed.850K.qc --cojo-file data/derived_data/cojo/fixed9/fixed9.ma --cojo-slct --out data/derived_data/cojo/fixed9/fixed9 --threads 56
```

### Angus

```{r}
read_table2(here::here("data/derived_data/grm_inbreeding/mizzou_hairshed.grm.id"),
            col_names = c("full_reg", "iid")) %>% 
  left_join(read_rds(here::here("data/derived_data/breed_key/breed_key.rds"))) %>% 
  mutate(keep = case_when(cross == "AN" ~ TRUE,
                          str_detect(full_reg, "AAA") ~ TRUE,
                          str_detect(full_reg, "BIR") ~ TRUE)) %>% 
  filter(keep == TRUE) %>% 
  select(full_reg, iid) %>% 
  write_delim(here::here("data/derived_data/cojo/an1/keep_list.an1.txt"),
              delim = " ",
              col_names = FALSE)
```

```
module load plink/plink-1.90b
srun -c 12 --account deckerlab plink --bfile data/raw_data/geno_dump/200924_HairShed.850K.qc --double-id --cow --threads 12 --keep data/derived_data/cojo/an1/keep_list.an1.txt --make-bed --out data/derived_data/cojo/an1/cojo.an1
```

```{r, eval=FALSE}
breeds_snp1101 %>% 
  filter(dataset == "an1") %>% 
  mutate(N = g0+g1+g2,
         #se = sqrt(var/(g0+g1+g2))) 
         )%>%
  left_join(bim) %>% 
  select(SNP, A1, A2, freq, b = b_value, var, p = p_value, N) %>% 
  filter(freq != 0) %>% 
  write_delim(here::here("data/derived_data/cojo/an1/an1.ma"),
              delim = " ")

```

```
srun --account deckerlab -p BioCompute,htc4,hpc5 -t 48:00:00 --mem 100G -c 56 source_functions/gcta_1.93.2beta/gcta64 --bfile data/derived_data/cojo/an1/cojo.an1 --cojo-file data/derived_data/cojo/an1/an1.ma --cojo-slct --out data/derived_data/cojo/an1/an1 --threads 56
```

### Brangus

```{r}
read_table2(here::here("data/derived_data/grm_inbreeding/mizzou_hairshed.grm.id"),
            col_names = c("full_reg", "iid")) %>% 
  left_join(read_rds(here::here("data/derived_data/breed_key/breed_key.rds"))) %>% 
  mutate(keep = case_when(cross == "BGR" ~ TRUE,
                          str_detect(full_reg, "BGR") ~ TRUE)) %>% 
  filter(keep == TRUE) %>% 
  select(full_reg, iid) %>% 
  write_delim(here::here("data/derived_data/cojo/bg1/keep_list.bg1.txt"),
              delim = " ",
              col_names = FALSE)
```

```
module load plink/plink-1.90b
srun -c 12 --account deckerlab plink --bfile data/raw_data/geno_dump/200924_HairShed.850K.qc --double-id --cow --threads 12 --keep data/derived_data/cojo/bg1/keep_list.bg1.txt --make-bed --out data/derived_data/cojo/bg1/cojo.bg1
```

```{r, eval=FALSE}
breeds_snp1101 %>% 
  filter(dataset == "bg1") %>% 
  mutate(N = g0+g1+g2,
         #se = sqrt(var/(g0+g1+g2))) 
         )%>%
  left_join(bim) %>% 
  select(SNP, A1, A2, freq, b = b_value, var, p = p_value, N) %>% 
  filter(freq != 0) %>% 
  write_delim(here::here("data/derived_data/cojo/bg1/bg1.ma"),
              delim = " ")

```

```
srun --account deckerlab -p BioCompute,htc4,hpc5 -t 48:00:00 --mem 100G -c 56 source_functions/gcta_1.93.2beta/gcta64 --bfile data/derived_data/cojo/bg1/cojo.bg1 --cojo-file data/derived_data/cojo/bg1/bg1.ma --cojo-slct --out data/derived_data/cojo/bg1/bg1 --threads 56
```

### Hereford

```{r, eval=FALSE}
read_table2(here::here("data/derived_data/grm_inbreeding/mizzou_hairshed.grm.id"),
            col_names = c("full_reg", "iid")) %>% 
  left_join(read_rds(here::here("data/derived_data/breed_key/breed_key.rds"))) %>% 
  mutate(keep = case_when(cross == "HFD" ~ TRUE,
                          str_detect(full_reg, "HER") ~ TRUE)) %>% 
  filter(keep == TRUE) %>% 
  select(full_reg, iid) %>% 
  write_delim(here::here("data/derived_data/cojo/hfd1/keep_list.hfd1.txt"),
              delim = " ",
              col_names = FALSE)
```

```
module load plink/plink-1.90b
srun -c 12 --account deckerlab plink --bfile data/raw_data/geno_dump/200924_HairShed.850K.qc --double-id --cow --threads 12 --keep data/derived_data/cojo/hfd1/keep_list.hfd1.txt --make-bed --out data/derived_data/cojo/hfd1/cojo.hfd1
```

```{r, eval=FALSE}
breeds_snp1101 %>% 
  filter(dataset == "hfd1") %>% 
  mutate(N = g0+g1+g2,
         #se = sqrt(var/(g0+g1+g2))) 
         )%>%
  left_join(bim) %>% 
  select(SNP, A1, A2, freq, b = b_value, var, p = p_value, N) %>% 
  filter(freq != 0) %>% 
  write_delim(here::here("data/derived_data/cojo/hfd1/hfd1.ma"),
              delim = " ")

```

```
srun --account deckerlab -p BioCompute,htc4,hpc5 -t 48:00:00 --mem 100G -c 56 source_functions/gcta_1.93.2beta/gcta64 --bfile data/derived_data/cojo/hfd1/cojo.hfd1 --cojo-file data/derived_data/cojo/hfd1/hfd1.ma --cojo-slct --out data/derived_data/cojo/hfd1/hfd1 --threads 56
```

### IGS

```{r}
read_table2(here::here("data/derived_data/aireml_varcomp/igs1/pull_list.txt"),
            col_names = c("full_reg")) %>% 
  mutate(iid = full_reg) %>% 
  select(full_reg, iid) %>% 
  write_delim(here::here("data/derived_data/cojo/igs1/keep_list.igs1.txt"),
              delim = " ",
              col_names = FALSE)
```

```
module load plink/plink-1.90b
srun -c 12 --account deckerlab plink --bfile data/raw_data/geno_dump/200924_HairShed.850K.qc --double-id --cow --threads 12 --keep data/derived_data/cojo/igs1/keep_list.igs1.txt --make-bed --out data/derived_data/cojo/igs1/cojo.igs1
```

```{r, eval=FALSE}
breeds_snp1101 %>% 
  filter(dataset == "igs1") %>% 
  mutate(N = g0+g1+g2,
         #se = sqrt(var/(g0+g1+g2))) 
         )%>%
  left_join(bim) %>% 
  select(SNP, A1, A2, freq, b = b_value, var, p = p_value, N) %>% 
  filter(freq != 0) %>% 
  write_delim(here::here("data/derived_data/cojo/igs1/igs1.ma"),
              delim = " ")

```

```
srun --account deckerlab -p BioCompute,htc4,hpc5 -t 48:00:00 --mem 100G -c 56 source_functions/gcta_1.93.2beta/gcta64 --bfile data/derived_data/cojo/igs1/cojo.igs1 --cojo-file data/derived_data/cojo/igs1/igs1.ma --cojo-slct --out data/derived_data/cojo/igs1/igs1 --threads 56
```

