---
title: "GEMMA notes"
author: "Harly Jane Durbin"
date: "2/18/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(dplyr)
```

```
wget https://github.com/genetics-statistics/GEMMA/releases/download/0.98.1/gemma-0.98.1-linux-static.gz
gemma-0.98.1-linux-static.gz
gzip -d gemma-0.98.1-linux-static.gz
chmod a+x gemma-0.98.1-linux-static.gz
./gemma-0.98.1-linux-static.gz
```

```{r}
#Lab IDs that don't have genotypes
read_table2("/CIFS/MUG01_N/deckerje/hjdzpd/hair_shedding/190215_gen/190214.hairshed_dump.NO_GEN", col_names = c("Lab_ID"))

read_table2("/CIFS/MUG01_N/deckerje/hjdzpd/hair_shedding/190215_gen/imputed/190215_hair_shedding.sample", col_names = FALSE)
```

Create dummy file same length as number of samples

```{r}
rep(1, 9148) %>% 
  as_tibble() %>% 
  write_delim(path = here::here("gwas/gemma/190215/190215.9148.pheno"), col_names = FALSE)
  
```


Calculate GRM: 
~/gemma-0.98.1-linux-static -g /CIFS/MUG01_N/deckerje/hjdzpd/hair_shedding/190215_gen/imputed/190215_hair_shedding.dose.mgf.gz -p /data/hjdzpd/hair_shed/gwas/gemma/190215/190215.9148.pheno -gk 2 -o 190215.9148

filename: date, # of individuals
Can't give absolute filepath because it appends `./output` to it, give only prefix