---
title: "Gentotype dump"
author: "Harly Durbin"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(dplyr)
library(tidyr)

source(here::here("source_functions/iterative_id_search.R"))
```

# Setup

```{r}
animal_table <- read_rds(here::here("data/raw_data/import_join_clean/animal_table.rds"))
```

```{r}
full_ped <- read_rds(here::here("data/derived_data/3gen/full_ped.rds"))
```

```{r}
cleaned <- read_rds(here::here("data/derived_data/import_join_clean/cleaned.rds"))
```

```{r}
sample_table <- 
  read_csv(here::here("data/raw_data/import_join_clean/200820_sample_sheet.csv"),
           trim_ws = TRUE,
           guess_max = 100000)
```

# Animals with Lab IDs

```{r}
geno_dump <-
  cleaned %>% 
  distinct(Lab_ID) %>% 
  bind_rows(full_ped %>% 
              distinct(Lab_ID)) %>% 
  distinct() %>% 
  filter(!is.na(Lab_ID))
```


```{r}
geno_dump %<>% 
  # Add in duplicate lab IDs
  bind_rows(geno_dump %>% 
              left_join(animal_table %>% 
                          select(duplicate, Lab_ID)) %>% 
              select(Lab_ID = duplicate) %>% 
              filter(!is.na(Lab_ID)) %>% 
              filter(Lab_ID != 0))
```

## How many also have sample IDs and should have acceptable genotypes?

```{r}
geno_dump %>% 
  left_join(sample_table %>% 
              select(Lab_ID = lab_id, sample_id, call_rate, do_not_analyze)) %>% 
  # Has sample ID
  filter(!is.na(sample_id)) %>% 
  # do_not_analyze = FALSE
  filter(is.na(do_not_analyze)) 
```

## Export Lab ID list

```{r}
geno_dump %>% 
  write_tsv(here::here("data/derived_data/geno_dump/200923.geno_dump.txt"), col_names = FALSE)
```

# Post-imputation tally

* 11,776 unique lab IDs with at least one sample ID not marked `do_not_analyze`
* Imputation pipeline removed:
    + 11 ULD 
    + 144 F250
    + 38 other assay

```{r}
fam <-
  read_table2(here::here("data/raw_data/geno_dump/200921_HairShed.850K.fam"), col_names = FALSE) %>% 
  select(international_id = X1) %>% 
  left_join(sample_table %>% 
              select(international_id, Lab_ID = lab_id)) %>% 
  distinct()
```

```{r}
full_ped %>% 
  left_join(animal_table %>% 
              select(Lab_ID, duplicate)) %>% 
  # left_join(fam,
  #           by = c("duplicate" = "Lab_ID")) %>% 
  # filter(!is.na(international_id))
  mutate(international_id = NA_character_) %>% 
  id_search(
    source_col = duplicate,
    search_df = fam,
    search_col = Lab_ID,
    key_col = international_id
  ) %>% 
  id_search(
    source_col = Lab_ID,
    search_df = fam,
    search_col = Lab_ID,
    key_col = international_id
  )  
```



# Commentary

