---
title: "Fixed effect BLUEs"
author: "Harly Durbin"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(tidyr)
library(stringr)
library(dplyr)
library(glue)
library(ggplot2)
library(magrittr)
library(tidylog)

source(here::here("source_functions/melt_aireml.R"))
source(here::here("source_functions/parse_renf90table.R"))

```

# Notes & questions


```{r}
breed_key <- read_rds(here::here("data/derived_data/breed_key/breed_key.rds"))
```


# Setup 

```{r, warning=FALSE, message=FALSE}
cleaned <- read_rds(here::here("data/derived_data/import_join_clean/cleaned.rds"))
```

```{r, warning=FALSE, message=FALSE}
full_ped <- read_rds(here::here("data/derived_data/3gen/full_ped.rds"))
```

```{r, warning=FALSE, message=FALSE}
fixed13 <-
  c(1:4) %>% 
  purrr::map_dfr(~ parse_renf90table(here::here("data/derived_data/base_varcomp/fixed2/renf90.tables"),
                                     effect_num = .x,
                                     effect_key = TRUE)) %>% 
  mutate(effect = case_when(effect == 1 ~ "year",
                            effect == 2 ~ "calving_season",
                            effect == 3 ~ "toxic_fescue",
                            effect == 4 ~ "age_group")) %>% 
  right_join(read_table2(here::here("data/derived_data/base_varcomp/fixed2/solutions"),
                         skip = 1,
                         col_names = c("trait", "effect", "id_renamed", "solution", "se")) %>%
               select(-trait) %>% 
               filter(!effect %in% c(7, 8)) %>% 
               mutate_at(vars("effect", "id_renamed"), ~ as.character(.)) %>% 
               mutate(effect = case_when(effect == 1 ~ "year",
                                         effect == 2 ~ "calving_season",
                                         effect == 3 ~ "toxic_fescue",
                                         effect == 4 ~ "age_group",
                                         effect == 5 ~ "mean_apparent_high",
                                         effect == 6 ~ "lat")))
  
  
```

# Age

```{r}
fixed2 %>% 
  filter(effect == "age_group") %>% 
  arrange(id_original) %>% 
  mutate(id_original = forcats::fct_inorder(as.factor(id_original))) %>% 
  ggplot(aes(x = id_original,
             y = solution)) +
  geom_bar(stat = "identity",
             position = "identity") +
  geom_errorbar(aes(ymin = solution - se,
                    ymax = solution + se)) +
  theme_classic() +
  scale_x_discrete(labels = c("1", "2-3", "4-7", "8+")) +
  theme(plot.title = element_text(size = 22,
                                  face = "italic",
                                  margin = margin(t = 0,
                                                  r = 0,
                                                  b = 13,
                                                  l = 0)),
        axis.title = element_text(size = 16),
        axis.title.y = element_text(margin = margin(t = 0,
                                                    r = 10,
                                                    b = 0,
                                                    l = 0)),
        axis.title.x = element_text(margin = margin(t = 10,
                                                    r = 0,
                                                    b = 0,
                                                    l = 0)),
        axis.text = element_text(size = 14),
        legend.position = "none") +
  labs(x = NULL,
       y = "BLUE")
```

# Days from May 1

```{r}
fixed1 %>% 
  distinct(effect)
```

