---
title: "Environmental variable reaction norm & GWAS"
author: "Harly Durbin"
output:
  html_document:
    toc: true
    toc_depth: 2
    df_print: paged
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
library(readr)
library(tidyr)
library(stringr)
library(dplyr)
library(glue)
library(readxl)
library(ggplot2)
library(magrittr)
library(purrr)
#library(tidylog)

source(here::here("source_functions/melt_aireml.R"))
source(here::here("source_functions/parse_renf90table.R"))
source(here::here("source_functions/lrt_calc.R"))
source(here::here("source_functions/parse_loglik.R"))
source(here::here("source_functions/calculate_acc.R"))
```

# Notes & questions

## Model key

* `length1` and `temp1`
    + Homogenous residuals

# Setup 

```{r}
cleaned <- read_rds(here::here("data/derived_data/import_join_clean/cleaned.rds"))
```

```{r}
full_ped <- read_rds(here::here("data/derived_data/3gen/full_ped.rds"))
```

```{r}
length2 <-
  read_table2(here::here("data/derived_data/random_regression/length2/solutions"),
            skip = 1,
            col_names = c("trait", "effect", "id_renamed", "solution", "se")) %>% 
  select(-trait) %>% 
  mutate(effect = case_when(effect == 1 ~ "year",
                            effect == 2 ~ "calving_season",
                            effect == 3 ~ "toxic_fescue",
                            effect == 4 ~ "age_group",
                            effect == 5 ~ "day_length",
                            effect == 6 ~ "intercept",
                            effect == 7 ~ "slope_add",
                            effect == 8 ~ "intercept_add",
                            effect == 9 ~ "slope_pe",
                            effect == 10 ~ "intercept_pe"))
```

```{r}
length1 <-
  read_table2(here::here("data/derived_data/random_regression/length1/solutions"),
            skip = 1,
            col_names = c("trait", "effect", "id_renamed", "solution", "se")) %>% 
  select(-trait) %>% 
  mutate(effect = case_when(effect == 1 ~ "year",
                            effect == 2 ~ "calving_season",
                            effect == 3 ~ "toxic_fescue",
                            effect == 4 ~ "age_group",
                            effect == 5 ~ "slope_add",
                            effect == 6 ~ "intercept_add",
                            effect == 7 ~ "slope_pe",
                            effect == 8 ~ "intercept_pe")) %>% 
  left_join(read_table2(here::here("data/derived_data/random_regression/length1/renadd05.ped"),
                        col_names = FALSE) %>% 
              select(id_renamed = X1,
                     full_reg= X10))
```

# Data summary

```{r}
length2 %>% 
  filter(effect %in% c("slope_add")) %>% 
  mutate(acc = purrr::map_dbl(.x = se,
                              ~ calculate_acc(e = 0.70788,
                                              u = 0.14733,
                                              se = .x,
                                              option = "reliability"))) %>% 
  bind_rows(length2 %>% 
              filter(effect %in% c("intercept_add")) %>% 
              mutate(acc = purrr::map_dbl(.x = se,
                                          ~ calculate_acc(e = 0.70788,
                                                          u = 0.48791,
                                                          se = .x,
                                                          option = "reliability")))) %>% 
  arrange(desc(acc))
```

```{r}
full_ped %>% 
  filter(sire_reg != "0") %>% 
  group_by(sire_reg) %>% 
  tally(sort = TRUE) %>% 
  ungroup() %>% 
  top_n(15, n) %>% 
  select(full_reg = sire_reg) %>% 
  left_join(length1) %>% 
  filter(str_detect(effect, "add")) %>% 
  select(full_reg, effect, solution) %>% 
  pivot_wider(id_cols = full_reg,
              values_from = "solution",
              names_from = effect) %>% 
  mutate(Breed = case_when(str_detect(full_reg, "AAA") ~ "Angus",
                           str_detect(full_reg, "HER") ~ "Hereford",
                           str_detect(full_reg, "SIM") ~ "Simmental")) %>% 
  ggplot() +
  geom_abline(aes(intercept = intercept_add,
                  slope = slope_add,
                  color = Breed)) +
  ylim(-3, 3) +
  xlim(-3, 3) +
  labs(x = "Centered day length",
       y = "Centered day length")
```

```{r}
read_table2(here::here("data/derived_data/random_regression/length1/data.txt"),
            col_names = FALSE) %>% 
  select(day_length = X6) %>% 
  distinct() %>% 
  ggplot(aes(x = day_length,
             y = day_length)) +

```


# Commentary