---
title: "Pedigree corrections using `seekparentf90`"
author: "Harly Durbin"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(dplyr)
library(ggplot2)
```

# Notes & questions

# Setup

```{r, warning=FALSE, message=FALSE}
cleaned <- read_rds(here::here("data/derived_data/import_join_clean/cleaned.rds"))
```

```{r, warning=FALSE, message=FALSE}
full_ped <- read_rds(here::here("data/derived_data/3gen/full_ped.rds"))
```

```{r}
conflicts <-
  read_table2(here::here("data/derived_data/seekparentf90/Parent_Progeny_Conflicts.condensed.txt"),
              col_names = FALSE) %>% 
  select(comparison = X1,
         full_reg = X2, 
         parent_reg = X3,
         n_conflicts = X4, 
         percent_conflicts = X6) 

```

```{r}
trio_conflicts <-
  read_table2(here::here("data/derived_data/seekparentf90/Parent_Progeny_Conflicts_Trio.condensed.txt"),
              col_names = FALSE) %>% 
  filter(X1 == "Animal-Sire-Dam") %>% 
  select(full_reg = X2, 
         sire_reg = X3,
         dam_reg = X4,
         trio_conflicts = X5, 
         percent_trio_conflicts = X7,
         trio_result = X20) %>% 
  left_join(read_table2(here::here("data/derived_data/seekparentf90/Parent_Progeny_Conflicts_Trio.condensed.txt"),
                        col_names = FALSE) %>% 
              filter(X1 == "Animal-Sire") %>% 
              select(full_reg = X2,
                     sire_reg = X3,
                     sire_conflicts = X4,
                     percent_sire_conflicts = X6,
                     sire_result = X16)) %>% 
  left_join(read_table2(here::here("data/derived_data/seekparentf90/Parent_Progeny_Conflicts_Trio.condensed.txt"),
                        col_names = FALSE) %>% 
              filter(X1 == "Animal-Dam") %>% 
              select(full_reg = X2,
                     dam_reg = X3,
                     dam_conflicts = X4,
                     percent_dam_conflicts = X6,
                     dam_result = X16)) %>% 
  select(contains("reg"), contains("result"), contains("percent"), contains("conflicts"))
```

# Plot

```{r}
conflicts %>%
  filter(2.5 >= percent_conflicts) %>% 
  ggplot(aes(x = percent_conflicts)) +
  geom_density()
```

```{r}
conflicts %>%
  filter(2.5 >= percent_conflicts) %>% 
  ggplot(aes(x = percent_conflicts)) +
  geom_histogram(bins = 40) + 
  geom_vline(xintercept = 0.25) +
  labs(x = "Percent discordant", 
       y = "N comparisons")
```

# Incorrect genotypes

At what number of incorrect failed comparisons parent-progeny comparisons do you exclude an animal???

```{r}
single_tally <-
  conflicts %>% 
  filter(0.5 > percent_conflicts) %>% 
  group_by(parent_reg) %>% 
  summarise(pass_single = n()) %>% 
  full_join(conflicts %>% 
              filter(percent_conflicts >= 0.5) %>% 
              group_by(parent_reg) %>% 
              summarise(fail_single = n())) %>% 
  arrange(desc(fail_single)) %>% 
  replace_na(list(pass_single = 0, fail_single = 0)) 
```

```{r}
trio_tally <-
  trio_conflicts %>% 
  filter(0.5 > percent_sire_conflicts) %>% 
  group_by(sire_reg) %>% 
  summarise(pass_trio = n()) %>% 
  full_join(trio_conflicts %>% 
              filter(percent_sire_conflicts >= 0.5) %>% 
              group_by(sire_reg) %>% 
              summarise(fail_trio = n())) %>% 
  replace_na(list(pass_trio = 0, fail_trio = 0))
```

```{r}
trio_tally %>% 
  left_join(single_tally %>% 
              rename(sire_reg = parent_reg)) %>% 
  arrange(desc(fail_trio))
```



# Create and export blacklist

```{r}
trio_conflicts %>% 
  filter(percent_trio_conflicts > 0.5) %>% 
  arrange(desc(percent_trio_conflicts))
```



```{r}
conflicts %>% 
  filter(result == "No-Match") %>% 
  group_by(parent_reg) %>% 
  tally() %>% 
  filter(n > 1) %>% 
  mutate(fid = parent_reg) %>% 
  select(parent_reg,
         fid) %>% 
  write_tsv(here::here("data/derived_data/seekparentf90/remove_genotype.txt"),
            col_names = FALSE)
```

```{r}
conflicts %>% 
  filter(percent_conflicts > 0.5) %>% 
  mutate(wrong_sire = if_else(stringr::str_detect(comparison, "Sire"),
                              "0",
                              NA_character_),
         wrong_dam = if_else(stringr::str_detect(comparison, "Dam"),
                              "0",
                              NA_character_)) %>% 
  select(full_reg, contains("wrong")) %>% 
  write_csv(here::here("data/derived_data/seekparentf90/parentage_conflicts.csv"),
            na = "")
  
```

