rules: ['setup_data', 'copy_par', 'renumf90', 'airemlf90', 'cleanup']

r_module: "r/r-3.6.2-python-2.7.14-tk"

mpi_module: "openmpi/openmpi-3.1.3-intel-16.0.2"

renumf90_path: "/storage/hpc/group/UMAG/WORKING/hjdzpd/mizzou_hairshed/source_functions/renumf90"

aireml_path: "/storage/hpc/group/UMAG/WORKING/hjdzpd/mizzou_hairshed/source_functions/airemlf90"

geno_prefix: "data/raw_data/geno_dump/200924_HairShed.850K"

#model: ['fixed2', 'fixed3', 'fixed4', 'fixed5', 'fixed6', 'fixed7', 'fixed8', 'fixed9', 'fixed10', 'fixed11', 'fixed12', 'fixed13', 'fixed14']

model: ['fixed14']
