rules: ['transpose_genotypes', 'format_genotypes', 'append_id', 'copy_par', 'renumf90', 'airemlf90']

model: "no_breed"

geno_prefix: "data/raw_data/geno_dump/200924_HairShed.850K"

plink_module: "plink/plink-1.90b"

plink_nt: 12

sample_ids: "data/raw_data/190215_hair_shedding.geno_key"

mapfile: "data/raw_data/190215_hair_shedding.chrinfo.txt"

renumf90_path: "/storage/hpc/group/UMAG/WORKING/hjdzpd/hair_shed/source_functions/renumf90"

aireml_path: "/storage/hpc/group/UMAG/WORKING/hjdzpd/hair_shed/source_functions/airemlf90"
