rules: ['setup_data', 'copy_par', 'renumf90', 'airemlf90']

r_module: "r/r-3.6.2-python-2.7.14-tk"

renumf90_path: "/storage/hpc/group/UMAG/WORKING/hjdzpd/mizzou_hairshed/source_functions/renumf90"

aireml_path: "/storage/hpc/group/UMAG/WORKING/hjdzpd/mizzou_hairshed/source_functions/airemlf90"

geno_prefix: "data/raw_data/geno_dump/200924_HairShed.850K"

model: ['fixed2', 'fixed3']
