rules: ['pheno_file', 'mlma']

gcta_path: "source_functions/gcta_1.93.2beta/gcta64"

mpi_module: "openmpi/openmpi-3.1.3-intel-16.0.2"

r_module: "r/r-3.6.2-python-2.7.14-tk"

geno_prefix: "data/raw_data/geno_dump/200924_HairShed.850K"

grm_path: "data/derived_data/gcta_gwas/mizzou_hairshed.grm.gz"

mlma_threads: 24

model: ['2016an', '2017an', '2018an', '2019an']
