rules: ['pheno_file', 'grm_keep', 'gcta_grm', 'mlma']

gcta_path: "source_functions/gcta_1.93.2beta/gcta64"

mpi_module: "openmpi/openmpi-3.1.3-intel-16.0.2"

r_module: "r/r-4.0.0-gcc-10.1.0"

plink_module: "plink/plink-1.90b"

plink_nt: 12

geno_prefix: "data/raw_data/geno_dump/200924_HairShed.850K"

gcta_grm_threads: 32

mlma_threads: 24

model: ['hfd1', 'an1', 'bg1', 'igs1', 'fixed15', 'fixed9']

dir: {'fixed9':['data/derived_data/aireml_varcomp/fixed9'], 'hfd1':['data/derived_data/aireml_varcomp/hfd1'], 'an1':['data/derived_data/aireml_varcomp/an1'], 'bg1':['data/derived_data/aireml_varcomp/bg1'], 'igs1':['data/derived_data/aireml_varcomp/igs1'], 'fixed15':['data/derived_data/aireml_varcomp/fixed15']}

animal_effect: {'fixed9':['2'], 'hfd1':[2], 'an1':[2], 'bg1':[2], 'igs1':[2], 'fixed15':[4]}

gen_var: {'fixed9':['0.33133'], 'hfd1':['0.21463'], 'an1':['0.35806'], 'bg1':['0.26718'], 'igs1':['0.39053'], 'fixed15':['0.32491']}

h2: {'fixed9':['0.3675115'], 'hfd1':['0.320991'], 'an1':['0.3700003'], 'bg1':['0.3988189'], 'igs1':['0.4072084'], 'fixed15':['0.3628175']}
