rules: ['gcta_grm']

gcta_path: "source_functions/gcta_1.93.2beta/gcta64"

mpi_module: "openmpi/openmpi-3.1.3-intel-16.0.2"

geno_prefix: "data/raw_data/geno_dump/200924_HairShed.850K"

gcta_grm_threads: "24"
