rules: ['gemma_grm', 'setup_data', 'plink_keep_sort', 'replace_fam', 'gemma']

r_module: "r/r-3.6.2-python-2.7.14-tk"

plink_module: "plink/plink-1.90b"

mpi_module: "openmpi/openmpi-3.1.3-intel-16.0.2"

gemma_path: "source_functions/gemma-0.98.3-linux-static"

plink_nt: 12

geno_prefix: "data/raw_data/geno_dump/200924_HairShed.850K"

year: ['2016', '2017', '2018', '2019', '2020']

var: ['day_length', 'temp']
