rules: ['setup_snp1101', 'snp1101']

r_module: "r/r-3.6.2-python-2.7.14-tk"

mpi_module: "openmpi/openmpi-3.1.3-intel-16.0.2"

renumf90_path: "/storage/hpc/group/UMAG/WORKING/hjdzpd/mizzou_hairshed/source_functions/renumf90"

aireml_path: "/storage/hpc/group/UMAG/WORKING/hjdzpd/mizzou_hairshed/source_functions/airemlf90"

snp1101_path: "/storage/hpc/group/UMAG/SCRIPTS/snp1101/snp1101"

geno_prefix: "data/raw_data/geno_dump/200924_HairShed.850K"

model: ['fixed9', 'hfd1']

dir: {'fixed9':['data/derived_data/aireml_varcomp/fixed9'], 'hfd1':['data/derived_data/aireml_varcomp/hfd1']}

animal_effect: {'fixed9':['2'], 'hfd1':[2]}

gen_var: {'fixed9':['0.33138'], 'hfd1':['0.21463']}

h2: {'fixed9':['0.3676612'], 'hfd1':['0.320991']}
