rules: ['transpose_genotypes', 'format_genotypes', 'format_genotypes2', 'copy_par', 'renumf90', 'airemlf90']

model: "no_breed"

geno_prefix: "data/raw_data/190215_hair_shedding.hard"

java_module: "java/openjdk/java-1.8.0-openjdk"

sample_ids: "data/raw_data/190215_hair_shedding.geno_key"

mapfile: "data/raw_data/190215_hair_shedding.chrinfo.txt"

renumf90_path: "/storage/hpc/group/UMAG/WORKING/hjdzpd/hair_shed/source_functions/renumf90"

aireml_path: "/storage/hpc/group/UMAG/WORKING/hjdzpd/hair_shed/source_functions/airemlf90"
